[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[context.production.environment]
  # Variáveis de ambiente para produção
  ADMIN_PASSWORD_HASH = "$2a$10$Qk2Qw8Qw8Qw8Qw8Qw8Qw8uLOickgx2ZMRZoMyu" # hash de '1'
  USER_PASSWORD_HASH = "$2a$10$Qk2Qw8Qw8Qw8Qw8Qw8Qw8uLOickgx2ZMRZoMyu" # hash de '2'