[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[context.production.environment]
  # Variáveis de ambiente para produção
  ADMIN_PASSWORD_HASH = "$2a$10$N9qo8uLOickgx2ZMRZoMy.MQDqSh2QfR5g/Jdb1Q9.3Z5eJY4mCqW" # hash de 'admin123'
  USER_PASSWORD_HASH = "$2a$10$N9qo8uLOickgx2ZMRZoMy.MQDqSh2QfR5g/Jdb1Q9.3Z5eJY4mCqW" # hash de 'tropa123'